app_name: "Food and drink"
max_category_name_length: 50
max_content_length: 1000
min_content_length: 1
min_quantity: 1
max_quantity: 100
min_price: 0.01
max_price: 50
max_address_length: 200
max_phone_length: 20
valid_phone_regex: "\\A(0|\\+84)[35789]\\d{8}\\z"
max_product_name_length: 100
max_description_length: 1000
min_rating: 1
max_rating: 5
max_comment_length: 1000
min_comment_length: 1
max_name_length: 100
max_email_length: 100
valid_email_regex: \A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z
min_password_length: 6
pagy_items: 8
home_page_items: 4
image_types: ["image/jpeg", "image/png", "image/gif"]
max_image_size: 5
sort_name_asc: "name-asc"
sort_name_desc: "name-desc"
sort_price_asc: "price-asc"
sort_price_desc: "price-desc"
